### ISSUE TITLE
API isn't working

### ISSUE THREAD

**Issue by yagop** [guluc3m/gul-gultalks#29]
According to the API, the conferences route is `/conferences/:id` but the actual is `/:id`. We could add this one:

```ruby
  match 'conference', to: 'conferences#show', via: :get, path: '/conferences/:id', id: /\d+/
```

Since the project uses Friendly URLs, conferences and other models are initialized with `friendly`. I can't get them by the ID as the API says.

```ruby
@conference = Conference.friendly.find(params[:id])
```

To maintain both URLs, we could do something like this, but dunno if there is a better way:

```ruby
class ConferencesController < ApplicationController
  [...]
  def show
    # Not a friendly url, just the real ID.
    if params[:id].to_i != 0
      @conference = Conference.find(params[:id])
    else
      @conference = Conference.friendly.find(params[:id])
    end

**Comment by miguxbe** [comment]
Yes, thanks, we know that the API/docs are very outdated and a little messy. But before start to rewrite we should argue the full structure of the API to be all agree and cover the requirements.

**Comment by rmed** [comment]
Ok, some points:
- Yes API documentation is VERY outdated.
- Request to obtain details of a conference is done to `/:conference_id`. I've just tested this and it works with either a slug or a numeric ID.
- Request to obtain events for a specific conference is done to `/:conference_id/events`
- Request to obtain a specific event from a conference is done to `/:conference_id/:event_id`
- Request to obtain ALL conferences and ALL events (Zoe and stuff) is done to `/conferences` (at least for the moment, may speak with @voiser about this one to use `/all` or something like that instead).

**Comment by yagop** [comment]
My fault, about numeric, it's working as `/:conference_id`

```bash
curl "http://cursos.gul.es/3" -H "Accept: application/json"
{"id":3,"title":"XXVI Jornadas Técnicas del GUL","description":"XXVI Jornadas Técnicas del Grupo de Usuarios de Linux de la Universidad Carlos III de Madrid, marzo 2015","location":"Leganés","start_date":"2015-04-20","end_date":"2015-04-24","coordinator":"Adrián Borja Pimentel","active":true,"call_for_papers_enabled":true,"voting_enabled":false,"show_calendar":false,"call_for_papers_start_date":"2015-03-15","call_for_papers_end_date":"2015-03-29","voting_start_date":"2015-03-30","voting_end_date":"2015-04-12","slug":"xxvi-jornadas-tecnicas-del-gul","created_at":"2015-03-15T21:14:44.000Z","updated_at":"2015-03-16T22:17:23.000Z"}
```

`/conferences` is also working as expected, thanks.

**Comment by miguxbe** [comment]
So I proceed to close the issue.
