### ISSUE TITLE
E_TOOMANYGEMS

### ISSUE THREAD

**Issue by javierhonduco** [guluc3m/gul-gultalks#42]
I know this issue has not a straightforward solution, but we have, IMO, too many gems.
Maybe we can reconsider some of them!

**Comment by miguxbe** [comment]
Well, at first sight it might seem that the project has many gems. But the initial idea was not to code everything from scratch. So we tried to compose everything with gems with a good code base and acceptably maintained packages, putting the sight into the modularity and possible future changes coming from other maintainers.

**Comment by javierhonduco** [comment]
Yeah, I totally agree with you and think those are quite good decisions :).
It was just a small obvious rant :)
